server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${STREAMING_KAFKA_BROKER_URL:localhost:9092}
    producer-timeout: ${KAFKA_PRODUCER_TIMEOUT:3000}
    producer-retries: ${KAFKA_PRODUCER_RETRIES:10}

charges:
  stream:
    group-id: company-metrics-consumer
    topic: stream-company-charges
    retry-attempts: 4
    backoff-delay: 100

logger:
  namespace: company-metrics-consumer

api:
  endpoint: ${COMPANY_METRICS_DATA_API_URL:localhost}

company-metrics:
  consumer:
    charges:
      enable: true