server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${STREAMING_KAFKA_BROKER_URL:localhost:9092}
    producer-timeout: ${KAFKA_PRODUCER_TIMEOUT:3000}
    producer-retries: ${KAFKA_PRODUCER_RETRIES:10}

charges:
  stream:
    group-id: company-metrics-consumer
    topic: stream-company-charges
    retry-attempts: 4
    backoff-delay: 100
    enable: true

logger:
  namespace: company-metrics-consumer

api:
  api-url: ${COMPANY_METRICS_API_URL:https://localhost}
  company-metrics-api-key: ${COMPANY_METRICS_API_KEY:localhost}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: company-metrics-consumer/healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true
