server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${STREAMING_KAFKA_BROKER_URL:localhost:9092}
    listener:
      concurrency: ${COMPANY_METRICS_LISTENER_CONCURRENCY:1}

company-metrics:
  consumer:
    charges:
      stream:
        enable: ${COMPANY_METRICS_CONSUMER_CHARGES_ENABLED:true}
        group-id: ${COMPANY_METRICS_CONSUMER_CHARGES_GROUP_ID:company-metrics-consumer}
        topic: ${COMPANY_METRICS_CONSUMER_CHARGES_TOPIC:stream-company-charges}
        retry-attempts: ${COMPANY_METRICS_CONSUMER_CHARGES_ATTEMPTS:4}
        backoff-delay: ${COMPANY_METRICS_CONSUMER_CHARGES_BACKOFF_DELAY:100}

    appointments:
      stream:
        enable: ${COMPANY_METRICS_CONSUMER_OFFICERS_ENABLED:true}
        group-id: ${COMPANY_METRICS_CONSUMER_OFFICERS_GROUP_ID:company-metrics-consumer}
        topic: ${COMPANY_METRICS_CONSUMER_OFFICERS_TOPIC:stream-company-officers}
        retry-attempts: ${COMPANY_METRICS_CONSUMER_OFFICERS_ATTEMPTS:4}
        backoff-delay: ${COMPANY_METRICS_CONSUMER_OFFICERS_BACKOFF_DELAY:100}

logger:
  namespace: company-metrics-consumer

api:
  api-url: ${COMPANY_METRICS_API_URL:https://localhost}
  company-metrics-api-key: ${COMPANY_METRICS_API_KEY:localhost}


management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: company-metrics-consumer/healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true
