server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${STREAMING_KAFKA_BROKER_URL:localhost:9092}
    producer-timeout: ${KAFKA_PRODUCER_TIMEOUT:3000}
    producer-retries: ${KAFKA_PRODUCER_RETRIES:10}

charges:
  stream:
    group-id: company-metrics-consumer
    topic:
      main: stream-company-charges

logger:
  namespace: company-metrics-consumer

api:
  api-url: ${API_URL:localhost}
  company-metrics-api-key: ${COMPANY_METRICS_API_KEY:localhost}

company-metrics:
  consumer:
    charges:
      enable: true
