server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1

charges:
  stream:
    enable: true
    group-id: company-metrics-consumer
    topic: stream-company-charges
    retry-attempts: 3
    backoff-delay: 10

logger:
  namespace: company-metrics-consumer

api:
  api-url: http://localhost:8888
  company-metrics-api-key: ${COMPANY_METRICS_API_KEY:localhost}

wiremock:
  server:
    port: 8888
